### ISSUE TITLE
Migrating data links broken

### ISSUE THREAD

**Issue by lindsgant** [archesproject/arches-docs#121]
Under the [ migrating from v.3 to v.4 tab](https://arches.readthedocs.io/en/stable/v3-to-v4-migration/), the hyperlinks from the 'See Also' section are broken. See attached image: 

##### which release does this issue concern?
stable / all versions

![archesdoxError](https://user-images.githubusercontent.com/52046075/60605575-a44d3f00-9d6e-11e9-94f8-75d8364383d1.png)

**Comment by mradamcox** [comment]
Thanks @lindsgant , when poking around on the docs I've found some other broken links too. I'll be updating this v3-v4 stuff today, and will look into this.

**Comment by lindsgant** [comment]
Thanks! I've been catching up on documentation (I am new to the GCI Arches team) so I'll note any other issues if I see them

**Comment by mradamcox** [comment]
@lindsgant I found a lot of other places that all used this same style of linking which worked on local builds but not when it was published on RTD. All fixed up now, so I'm closing this ticket. Thanks!
