### ISSUE TITLE
'Uploaded files' section in Read The Docs

### ISSUE THREAD

**Issue by reubenosborne1** [archesproject/arches-docs#125]
(In my opinion) There should be a section regarding how apache handles uploaded files in the read the docs https://arches.readthedocs.io/en/stable/serving-arches-with-apache/. 
Something along the lines of: 

**In settings.py** 
`MEDIA_URL= '/files/'`

**In /etc/apache2/sites-enabled/000-default.conf**
`Alias /files/uploadedfiles /home/user/project/project/uploadedfiles`
`<Directory /home/user/project/project/files/uploadedfiles>`
`Require all granted`
`</Directory>`

This would have been helpful to me as a new user!

**Comment by mradamcox** [comment]
@reubenosborne1 I've just made a big update to the entire Apache section, and would appreciate if you could have a look over it and let me know what you think. It should cover the changes needed for this ticket as well.

https://arches.readthedocs.io/en/latest/serving-arches-with-apache/
