### ISSUE TITLE
Document CouchDB install

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches-docs#15]
Right now, the CouchDB install is in the install script for Ubuntu and Docker.

It should also be documented as a requirement and eventually, what the management commands are.

**Comment by mradamcox** [comment]
To what version of Arches will this be relevant?

**Comment by jmunowitch** [comment]
It should be in the Releases of the ticket:
![image](https://user-images.githubusercontent.com/1542229/39202070-b7147114-47a5-11e8-85b7-a606c3e4fbda.png)

**Comment by mradamcox** [comment]
Which ticket are you referring to? We don't have releases in this repo, it would confuse our RTD setup(s). I will make some labels in here though.

**Comment by mradamcox** [comment]
@jmunowitch just looking back at this, I realize now that you were talking about ZenHub releases, which don't show up unless you have installed the ZenHub browser extension, and have signed into github. I think I'd prefer to just use the basic "release" labels so the tickets and their status are as accessible to people as possible (i.e. no need to have a github account, or to install the browser extension). If we need to set up more complex issue tracking, I'd like to first look at GH Projects, before going to something more complex like ZenHub. Thoughts?

**Comment by mradamcox** [comment]
Before closing this commit, I think I'd like to require a little more info in the docs about the role that couchdb plays. Minimal, but at least something.

**Comment by mradamcox** [comment]
Actually, what's in there looks good (I'd forgotten there already is a note), closing now.
