### ISSUE TITLE
Installation scripts documentation update

### ISSUE THREAD

**Issue by natuk** [archesproject/arches-docs#164]
##### describe the issue
The documentation indicates that on Linux ElasticSearch is not installed through the dependency installation scripts, but the script for [Ubuntu 18.04](https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_setup.sh) appears to install it. I ran the script and indeed I now have an ElasticSearch service running.

##### please add links to existing docs or code (if relevant)
The information appears on this page:
https://github.com/archesproject/arches-docs/blob/4.4.3/docs/requirements-and-dependencies.txt
which is rendered over here:
https://arches.readthedocs.io/en/stable/requirements-and-dependencies/

##### which release does this issue concern?
stable

**Comment by mradamcox** [comment]
This should be taken care of now, as appropriate in /stable and /latest. @natuk I'll let you confirm and close the ticket.

**Comment by natuk** [comment]
Yes, thank you.
