### ISSUE TITLE
CouchDB screens on headless Ubuntu

### ISSUE THREAD

**Issue by natuk** [archesproject/arches-docs#165]
#### describe the issue
On a headless Ubuntu 18.04 installation, running the script to install dependencies requires manual input for the CouchDB installation, i.e. choosing IP address for the service to respond to and choosing username and password. The documentation pages do not cover this part of the dependency installation and it would be useful to have this covered as it is then referred to further down in the page in relation to the mobile app.

##### please add links to existing docs or code (if relevant)
The extra information should appear here:
https://arches.readthedocs.io/en/stable/requirements-and-dependencies/#software-dependencies
and refer to the section further down in the same page (about CouchDB).
Editable page: https://github.com/archesproject/arches-docs/blob/4.4.3/docs/requirements-and-dependencies.txt

##### which release does this issue concern?
stable

**Comment by mradamcox** [comment]
This is now covered by https://github.com/archesproject/arches-docs/commit/ae80c2dd99845d99a320e94dd6898de2766ff8eb, which is currently visible in the in-progress docs branch here: https://arches.readthedocs.io/en/dev-5.1/configuring-arches/#arches-collector-checklist.
