### ISSUE TITLE
pip does not come with Python on Ubuntu headless

### ISSUE THREAD

**Issue by natuk** [archesproject/arches-docs#166]
#### describe the issue
Documentation says that Python 2.7.9 and higher includes `pip`. However on Ubuntu 18.04 (with Python 2.7.17) running the command `pip install virtualenv` brings up the message:

> Command pip not found but can be installed with: sudo apt install python-pip

Consider adding a line in the [dependency installation script](https://github.com/archesproject/arches/blob/master/arches/install/ubuntu_setup.sh) to install pip.

##### please add links to existing docs or code (if relevant)
This is where the statement is made:
https://arches.readthedocs.io/en/stable/requirements-and-dependencies/#software-dependencies

This is where `pip` is required for the first time:
https://arches.readthedocs.io/en/stable/installation/

##### which release does this issue concern?
stable

**Comment by mradamcox** [comment]
Closing now. This issue is no longer relevant because we have moved to Python 3.7, which does include pip (as well as `venv`, so virtualenv is also no longer necessary).
