### ISSUE TITLE
Document Ability to order business data loading in packages

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches-docs#17]
See https://github.com/archesproject/arches/issues/3268.

An example: https://github.com/archesproject/lincoln_release/blob/master/package_config.json

**Comment by ryan86** [comment]
Documentation Notes:

- To specify the order of your business data load, list the csv or json files in the order you would like them to be loaded in your package_config.json file
- The package_config.json -> business_data_load_order property determines the order in which files will be loaded using the load_package command

Separate but related note:
- The settings.BUSINESS_DATA_FILES setting in settings.py determines the load order of files using the import_business_data command if you do not pass an argument for the -s parameter
