### ISSUE TITLE
Document Card Components in general 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-docs#175]
Create a section in the docs that shows users how to specify a card component.
Currently, the documentation for the ["Cards Tab"](https://arches.readthedocs.io/en/stable/designing-the-database/#cards-tab) doesn't even mention Card components.  This UI should be updated and then there should be subsections for each type of card component describing what they do (see other tickets).

**Comment by whatisgalen** [comment]
https://arches.readthedocs.io/en/latest/designing-the-database/

**Comment by apeters** [comment]
I would split out these 2 sentences.

```The “CSS Classes” enables a user to enter space-separated class names (e.g. card-empty-class card-incomplete-class) that correspond to class names defined by a developer in package.css. While card components can be created from scratch, arches (v5 on) comes with a few out of the box:```

Also I would mention that the `CSS Classes` is an input, as in `The "CSS Classes" input box enables a user.....`

**Comment by mradamcox** [comment]
Addressed above comment in `dev-5.1` and now closing.
