### ISSUE TITLE
Document Related Resources Map Card Component

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-docs#177]
Document how/why to use the Related Resources Map Card Component

**Comment by whatisgalen** [comment]
https://arches.readthedocs.io/en/latest/designing-the-database/

**Comment by apeters** [comment]
there is a grammatical mistake in the text describing the card component:

``` This card component is very useful if a user knows primarily knows the geographic context of a resource```

**Comment by coherit** [comment]
fixed in dev-5.1
