### ISSUE TITLE
Installation instructions in readme.txt

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#207]
@azaroth42 commented on [Tue Mar 24 2020](https://github.com/archesproject/arches-for-science-prj/issues/94)

The generic installation instructions from the referenced page in the readme file don't work for the package, at least in the current state.

In particular:
- [ ] Need to run `python ./manage.py setup_db`, not packages -o setup_db
- [ ] missing `media/img/landing/museum_at_night.jpg`, I copied a random-ish image there
- [ ] no instructions for how to load the models, for /this/ package. I did: `python ./manage.py packages -o load_package -s afs/pkg/`
- [ ] `cd afs ; rm yarn.lock ; yarn install --network-timeout 1000000`

**Comment by mradamcox** [comment]
@azaroth42 Could you clarify which readme file you're referring to here? I'm thinking https://github.com/archesproject/arches/blob/master/README.md, as I think there was a txt version of that file before.

**Comment by mradamcox** [comment]
Additionally, I see this file in the arches project template: https://github.com/archesproject/arches/tree/master/arches/install/arches-templates, which is the file that would be in the arches-for-science-prj repo where you originally put this ticket. I'll put a ticket on the arches repo to update that txt file, mainly because it should now be an md file and have updated links.

**Comment by mradamcox** [comment]
https://github.com/archesproject/arches/issues/6692

**Comment by azaroth42** [comment]
It's from https://github.com/archesproject/arches-for-science-prj/issues/94 so I was referring in that particular case to the Arches for Science readme file, which is indeed the generic one from the project template :)

**Comment by mradamcox** [comment]
Ok, could you clarify where the "generic installation instructions from the referenced page in the readme" are? Just trying to figure out what to do with this ticket.

**Comment by azaroth42** [comment]
Probably this: 
> The Arches Installation Guide and Arches User Guide are available [here](http://archesproject.org/documentation/). 

Which might have been updated since?

**Comment by mradamcox** [comment]
Yeah, makes sense. I'll close this ticket now. We have plenty of other installation-related documentation work to do, so the specific problems you mentioned in this ticket will get handled elsewhere along the way. The image issue is just for afs so maybe a new ticket in that repo just for that issue would be helpful.
