### ISSUE TITLE
Document how to delete resources

### ISSUE THREAD

**Issue by coherit** [archesproject/arches-docs#224]
**describe the issue**
The docs include a section on creating resources, but does not cover how to delete resources.

**please add links to existing docs or code (if relevant)**
This content will live in a new section called Deleting Resources under Using Arches: https://github.com/archesproject/arches-docs/blob/dev-5.1/docs/deleting-resources.txt. 

Its content could be added to the in-app help when completed: https://github.com/archesproject/arches/blob/master/arches/app/templates/help/resource-editor-help.htm

**which release does this issue concern?**

**Comment by neilsilberman** [comment]
Please assign to me

**Comment by ekansa** [comment]
@neilsilberman @coherit I updated the documentation to include instructions to delete resource instances. I'm going to close this issue. If you would like to see additional revisions, please do create a new issue! Thanks!!
