### ISSUE TITLE
Serving w/ Apache docs out of date for static resources

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-docs#232]
#### describe the issue
https://arches.readthedocs.io/en/stable/serving-arches-with-apache/#handling-static-files 
Says there are two situations where you need to add configuration -- if you're running without DEBUG, or if you're running with, but static files are coming from somewhere else.

In the current codebase, you /always/ need to configure this. So the documentation should reflect that (or the codebase should be reverted to allow it to work).

Typos: There is also an extraneous `p` at the end of the example in step 4 ... and then step 5 is also labeled as step 4.

**Comment by mradamcox** [comment]
Related to #125

**Comment by mradamcox** [comment]
@azaroth42 I've just made a big update to the entire Apache section, and would appreciate if you could have a look over it and let me know what you think. It should cover the changes needed for this ticket as well.

https://arches.readthedocs.io/en/latest/serving-arches-with-apache/
