### ISSUE TITLE
New Accessibility Documentation

### ISSUE THREAD

**Issue by phudson-he** [archesproject/arches-docs#237]
#### describe the issue
A new document with information on how to develop in Arches with accessibility in mind.

##### please add links to existing docs or code (if relevant)
Currently working on the final draft document

##### which release does this issue concern?
All

**Comment by phudson-he** [comment]
@mradamcox Any ideas where this topic would sit in the document structure? Thanks.

**Comment by mradamcox** [comment]
Just to catch this thread up, we've put this content in a new section in Developing with Arches for now.
