### ISSUE TITLE
Updated documentation on apache deployment for ubuntu 20 / python 3

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#240]
#### describe the issue

Currently the documentation is targeted at ubuntu 18 or lower. 

##### please add links to existing docs or code (if relevant)

would also address #110

**Comment by mradamcox** [comment]
@whatisgalen What portion of the documentation is geared toward 16? https://arches.readthedocs.io/en/stable/serving-arches-with-apache/ I updated this section a few months ago and used python 3. Are there portions of it incompatible with Ubuntu 20?

**Comment by whatisgalen** [comment]
@mradamcox our most recent deployment at HPLA is on ubuntu 20 and python 3 and given that ubuntu20 already comes with apache2 and a few of its dependencies, we ran into issues specifically installing mod-wsgi and had to install it via `apt` for the whole system instead of via `pip` into the `venv`.

**Comment by mradamcox** [comment]
Ok, I reworked the section a little bit, and I think we're good to close this now.
