### ISSUE TITLE
Update CouchDB install documentation

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches-docs#242]
#### describe the issue
There current instructions for installing CouchDB 2.x on Ubuntu 20 (maybe also 18) throw an error.

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/latest/arches-collector-checklist/

##### which release does this issue concern?

latest

**Comment by mradamcox** [comment]
As far as I can tell, there isn't a way to install couchdb 2.x on Ubuntu 20 without Docker, so this documentation should note that. Also, this is directly tied to https://github.com/archesproject/arches/issues/6798.

**Comment by mradamcox** [comment]
A note should be added to the top of the docs section that points ubuntu 20 users here: https://docs.couchdb.org/en/stable/install/docker.html

**Comment by mradamcox** [comment]
Now addressed.
