### ISSUE TITLE
Update Cantaloupe config information

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-docs#244]
We removed the `cantaloupe` folder and are using the `uploadedfiles` folder instead. The documentation needs to reflect this.

**Comment by mradamcox** [comment]
@chrabyrd I'm guessing it would be a change in the example at the end of this line: https://github.com/archesproject/arches-docs/blob/master/docs/managing-and-hosting-iiif.txt#L14, and maybe a separate note? I'm not too familiar with Arches+Cantaloupe so I'm not sure where else it would need to be mentioned.

**Comment by mradamcox** [comment]
completed
