### ISSUE TITLE
GDAL version dependency update

### ISSUE THREAD

**Issue by aarongundel** [archesproject/arches-docs#250]
#### describe the issue
The GDAL version specified in the docs for dependencies doesn't exist.  

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/requirements-and-dependencies/

##### which release does this issue concern?
all

**Comment by mradamcox** [comment]
Based on the fact that we recommend Windows users install GDAL through OSGeo4W, I'm looking at this list https://trac.osgeo.org/osgeo4w/wiki/PackageListing and it seems like GDAL 2.2.x would be a reasonable version to put in the docs. @aarongundel if you installed gdal recently, what version did you end up with?

**Comment by aarongundel** [comment]
Hi @mradamcox - I'm on macos and I installed gdal 3.3.0 (latest version through brew) without issue. My comment was mostly that the macos version references a version that doesn't exist yet.

**Comment by mradamcox** [comment]
Gotchya. So I'll update to say 2.2.x, and then put 3.3.0 in the macos note.

**Comment by mradamcox** [comment]
Ultimately I just removed the note, it was from a long time ago and it sounds like no longer relevant.
