### ISSUE TITLE
Update CouchDB install directions

### ISSUE THREAD

**Issue by coherit** [archesproject/arches-docs#262]
#### describe the issue
The instructions to install CouchDB on Linux is using an outdated repository. 

#### suggested fix

Should now follow the CouchDB stable instructions (with the caveat of selecting the 2.3 install)

Replace 
`# only if you haven't already done this`
`wget --quiet -O - https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -`
`sudo add-apt-repository "deb https://apache.bintray.com/couchdb-deb $(lsb_release -sc) main"`
`sudo apt-get update`

With:

`sudo apt update && sudo apt install -y curl apt-transport-https gnupg`
`curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1`
`source /etc/os-release`
`echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main"  | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null` 

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/arches-collector-checklist/#arches-collector-checklist

##### which release does this issue concern?
5.x

**Comment by mradamcox** [comment]
Added this straight from the comment above... given that the Arches Collector is deprecated after v6 this isn't a high impact part of the documentation. https://community.archesproject.org/t/arches-collector-update/1580
