### ISSUE TITLE
Add Two-factor authentication documentation

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches-docs#268]
As of https://github.com/archesproject/arches/issues/8022 / https://github.com/archesproject/arches/pull/8079 , there will be an option to enable two-factor authentication in Arches. We should have documentation to support it.

**Comment by chrabyrd** [comment]
Needs discussion on branch

**Comment by mradamcox** [comment]
Just looking through the PR and the content looks good to me. I added a comment there.
