### ISSUE TITLE
Update IIIF Cantaloupe section

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#280]
#### describe the issue

As of writing, the section on generating IIIF Manifests is out of date. There is no longer a function needed to apply to a resource model. The `manifest_manger.py` view handles this in conjunction with the frontend Image Service Manager UI. The process for creating an Image Service is not documented. The part on editing the resource model is incomplete; only the IIIF card is specified, not the actual node needed to make the annotation. Furthermore, the documentation linked to from the official Cantaloupe foundation references an old version (3) which implementers have encountered some issues with. In general this section needs to be more fleshed out to be considered a full instruction on start to finish

##### please add links to existing docs or code (if relevant)

https://arches.readthedocs.io/en/stable/managing-and-hosting-iiif

##### which release does this issue concern?

6.0+, 5.2 and maybe 5.1 (tbd)

**Comment by mradamcox** [comment]
thanks @whatisgalen!
