### ISSUE TITLE
Add deprecation notes to documentation about Arches Collector mobile app

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#284]
#### describe the issue
As per the this [Arches form post](https://community.archesproject.org/t/arches-collector-update/1580) (dated Apr 19, 2022), Arches Collector will not be compatible with core Arches after the v7 release. This should be noted in all relevant documentation, and such documentation should probably be removed from the master branch ahead of the v7 release.

##### please add links to existing docs or code (if relevant)
for example: https://arches.readthedocs.io/en/stable/using-arches-collector/

Text search through the whole code-base should be performed too to make sure mentioned of the Arches Collector are removed where necessary.

##### which release does this issue concern?
add deprecation warnings to 6.1
remove documentation for => 7

**Comment by ekansa** [comment]
This issue has been addressed with the PRs above.
