### ISSUE TITLE
Add links to Release Notes to documentation

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#296]
#### describe the issue
We need to have an up-to-date list of links to release notes so that it is easy to find them from the documentation. This came up in https://github.com/archesproject/arches-docs/issues/295.

Preferably, the Arches Release Process section should be renamed Releases, add a list of links to the release notes there, and then move the existing information about the release process to a sub header or something like that.

Additionally, it may be nice to pull the actual release notes into the repo by downloading them and pushing them into .rst files in the docs. This could be scripted fairly easily, but I would say it's not as pressing as simply getting links in.

##### please add links to existing docs or code (if relevant)
[](https://arches.readthedocs.io/en/stable/release-process/)

##### which release does this issue concern?
6 and up

**Comment by ekansa** [comment]
I think we now have this: https://arches.readthedocs.io/en/stable/introduction/releases/ 

We can issue a new ticket, or reopen this if needed.
