### ISSUE TITLE
Clarify that Arches supports level 2 of the EDTF spec

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#298]
#### describe the issue
The docs don't clarify what level of the [EDTF spec](http://www.loc.gov/standards/datetime/) Arches supports. Arches supports level 2 of the spec, so that should be added to the section about default data types.

Also it would be good to note that `[../1920]` must be used instead of `../1920`, as per this discussion in the Arches forum: https://community.archesproject.org/t/what-level-of-the-edtf-spec-does-arches-support/1753

##### please add links to existing docs or code (if relevant)
[]
https://arches.readthedocs.io/en/stable/import-export/?highlight=edtf#edtf

##### which release does this issue concern?
5+

**Comment by ekansa** [comment]
Closing this issue after @mradamcox approved the PR with the suggested changes
