### ISSUE TITLE
Document Resource to Resource Relationship upload (.relations)

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#30]
We need to document how to import resource to resource relations using a .relations file. This was handled in v3 docs, but hasn't yet been added to v4 docs.

**Comment by mradamcox** [comment]
content can be pulled from this forum post (thanks @ryan86): https://groups.google.com/forum/#!topic/archesproject/HYuunQZGjts

**Comment by mradamcox** [comment]
To make a .relations file for testing, please see the 3.1.2 docs http://arches.readthedocs.io/en/3.1.2/arches-data/#from-arches, and scroll down to the .relations part of the section.

**Comment by adamlodge** [comment]
In this documentation, it would be good to  acknowledge the distinction between related resources and resource-instance data type, and address the differing upload workflows for the two.

**Comment by mradamcox** [comment]
@adamlodge that makes sense, though I think a brief note should suffice. Really, we need to add the `resource-instance` datatype to the value formats list http://arches.readthedocs.io/en/stable/import-export/#value-formats. I'll make separate issue for that.
