### ISSUE TITLE
Add information about deploying Arches with Docker

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#301]
#### describe the issue
Currently, the documentation links out to a core arches README that has docker build information in it.
![image](https://user-images.githubusercontent.com/10427268/214426291-76a86869-5d9f-4ceb-bac2-171c21d621ff.png)
https://github.com/archesproject/arches/tree/master/docker

We should discuss how more Docker related installation content can be moved into the official docs, whether a link to an image that is maintained by someone, or just some tips/tricks for how to approach building your own image.

**Comment by ekansa** [comment]
Yep. Until (if?) there's a more canonical Docker install option, we may want to provide more generic "tips and tricks" for using Docker to deploy Arches. We can ask in the community forum for examples of Docker deployments, hopefully get some collaboration going on identifying some good practices, and also link to some public repos that use Docker for deployment. 

At least then we will have a pretty good starting point to reduce pain, despair, frustration and ennui for developers that may want to experiment with using Docker for Arches.
