### ISSUE TITLE
Add note about extra Apache settings for asgiref TypeError

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#309]
#### describe the issue
I was getting this error in my Apache logs whenever I restarted apache: 

```
Exception ignored in: <function Local.__del__ at 0x7efe177b25e0>
Traceback (most recent call last):
  File "..../env/lib/python3.8/site-packages/asgiref/local.py", line 94, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7efe177b25e0>
Traceback (most recent call last):
  File "..../env/lib/python3.8/site-packages/asgiref/local.py", line 94, in __del__
NameError: name 'TypeError' is not defined
```

And this answer on stack exchange fixed it: https://stackoverflow.com/a/66571228/3873885

Add `WSGIApplicationGroup %{GLOBAL}` above the `WSGIDaemonProcess` section.

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/serving-arches-with-apache/#configure-apache

**Comment by ekansa** [comment]
@mradamcox I updated all of the v7 and v6 branches with this change. It looks like v5 and earlier documentation has pretty different Apache instructions, so I'm going to hold off on updating those in case I'm adding something that's not appropriate for those earlier versions. I'm no Apache expert so I'll be conservative with this edit.

**Comment by mradamcox** [comment]
Splendid, I think v5 is old enough at this point that documentation backports are very low priority. Thanks!
