### ISSUE TITLE
Document `packages -o seed_resource_tile_cache` command

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#31]
This command is not yet documented.

The code is here: https://github.com/archesproject/arches/blob/master/arches/app/views/tileserver.py#L129.

Documentation should happen in two places:

1. In command line reference, this should be brief as with all of the other commands in this section
2. In the Developing With Arches > Creating New Map Layers, I think it would be appropriate to make a new section called Caching Your Map Layers, where a more in-depth description of the operation should be placed. This new section should be referenced at the end of Managing Map Layers > Resource Layers.

**Comment by mradamcox** [comment]
@robgaston this ticket is so old... but I wonder if it will be obsolete with the removal of tilestache? is this seed command still operable?

**Comment by robgaston** [comment]
@mradamcox this ticket would only apply to pre-5 versions of Arches, as we are deprecating the existing tile server. there may ultimately be some replacement command, but that remains to be seen ATM

**Comment by mradamcox** [comment]
Obsolete, post-v5 release.
