### ISSUE TITLE
Add more detail to docs about managing celery with supervisor

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#310]
#### describe the issue
A bit more information about how to stop, start, etc. Celery once supervisor has been configured to manage it would be helpful. Content can be taken from this forum post: https://community.archesproject.org/t/how-to-shutdown-restart-celery-with-supervisor/1850

##### please add links to existing docs or code (if relevant)
It would probably be best to break this content up a little bit, https://arches.readthedocs.io/en/stable/setting-up-supervisord-for-celery/, one section for setting up supervisor + celery, and one for managing it once it supervisor is up and running.

**Comment by ekansa** [comment]
@mradamcox This is a good idea. This topic is also related to these two issues:

https://github.com/archesproject/arches/issues/9243

and

https://github.com/archesproject/arches/issues/9202

It'll be good to get some guidance from the Dev team about the purpose of supervisor and celery and how one should go about trouble-shooting. For me, with v7x celerybeat problems are a show stopper in production, but evidently you've had less of an issue with v6x.
