### ISSUE TITLE
Updating boto install and DEFAULT_FILE_STORAGE in S3 docs

### ISSUE THREAD

**Issue by SDScandrettKint** [archesproject/arches-docs#323]
#### describe the issue     
The following lines in the S3 + Arches documentation should be changed:
- Currently 3. states `pip install boto django-storages` , this should be updated to `pip install boto3 django-storages` to account for the updated boto3 that seems to have replaced boto.
- Within step 4.2 the DEFAULT_FILE_STORAGE should be replaced with 
`DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'` to incorporate usage of boto3.

- Additionally, if the version of Arches uses a version of Django that is <3.2, pip installing django-storages will install the latest version of django which will cause the application to break. This may only be relevant to when Arches is installed via git cloning rather than installing Arches via pip. To fix this I had to re-pip install the Arches requirements, though there may be a way to prevent the installation of django through this.
        

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/using-aws-s3/#steps-to-follow

##### which release does this issue concern?
all

**Comment by ekansa** [comment]
@SDScandrettKint Thanks for posting this issue with suggested fixes! I've incorporated your suggestions to a revised draft here:

https://arches.readthedocs.io/en/s3_7_3/using-aws-s3/

I also made a few edits to discuss other cloud storage providers so it doesn't read quite like an AWS advertisement. Please let me know if you think these changes properly reflect the current reality.
