### ISSUE TITLE
Docs: Workflow full code example incorrect

### ISSUE THREAD

**Issue by jlayt** [archesproject/arches-docs#328]
The Workflow Full Example js code still uses the old template definition method and should be updated to match the correct js template earlier on the page.

https://arches.readthedocs.io/en/stable/extensions/workflows/#full-example-workflow

**Comment by ekansa** [comment]
@jlayt @chiatt @mradamcox  I drafted an update to the documentation here:

https://arches.readthedocs.io/en/workflow_7_3/extensions/workflows/

I haven't actually made any workflow extensions yet. So it'll be good to check to see if I understood the new v7 extensions pattern and expressed those updates properly in the updated docs.

**Comment by chiatt** [comment]
Thanks @ekansa - this looks good to me
