### ISSUE TITLE
Related Resources Map Card Documentation

### ISSUE THREAD

**Issue by Habennin** [archesproject/arches-docs#355]
There is a card widget called "Related Resources Map Card" but what it does and how is not documented.

It would be helpful to document it.

<img width="374" alt="Screen Shot 2023-07-24 at 12 11 04 PM" src="https://github.com/archesproject/arches/assets/12068255/9b048e9c-7f78-43b8-b1b0-838860eddd57">

**Comment by ekansa** [comment]
@chiatt Is there any internal documentation or are the PRs that build this feature that I could review so I can understand this feature?

**Comment by ekansa** [comment]
This looks related to map geometries? https://github.com/archesproject/arches/issues/6574

**Comment by chiatt** [comment]
Hi @ekansa - There isn't any thing written up on it. Maybe we can find some time next week to walk through it.

**Comment by ekansa** [comment]
We actually have some documentation about this, but it is VERY hard to find. I'm going to add more cross references to make it easier to discover: https://arches.readthedocs.io/en/stable/administering/designing-the-database/#related-resources-map-card
