### ISSUE TITLE
Inform user of ENV activation when running frontend build

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#375]
Regarding instructions for creating a project, if the user is running Arches using a virtual environment, they need to have that environment activated for both the Django dev server as well as in the terminal in which they are running `yarn build_development`

This additional detail should probably be added in this section:
https://arches.readthedocs.io/en/stable/installing/installation/#build-a-frontend-asset-bundle

##### which release does this issue concern?
This concerns all 7.x releases; however, at a minimum it needs to be added to the current feature release (7.4.x).

**Comment by ekansa** [comment]
Thanks @chiatt I'm going to close this after updating the docs to not the virtual environment requirement.
