### ISSUE TITLE
Plugins "name" example should be updated for translations

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#398]
#### describe the issue

Currently the example for registering a plugin looks like this:
<img width="1154" alt="Screenshot 2024-02-05 at 4 30 58 PM" src="https://github.com/archesproject/arches-docs/assets/8366985/62447f83-c4ad-4fc5-8a75-b42a36a2bd1e">

But if you try to register a plugin following this example, you'll get an error for the "name" field since as of at least 7.5 the name should look like this: 
```
{"en": "Image Service Manager"}
```

##### please add links to existing docs or code (if relevant)

[here](https://arches.readthedocs.io/en/stable/developing/extending/extensions/plugins/)

**Comment by jacobtylerwalls** [comment]
Ah good call @whatisgalen. This is only as of dev/7.6, right? (#10517)

**Comment by jacobtylerwalls** [comment]
Actually @whatisgalen I just retested and the original example still works fine for me. Can you include the traceback and steps to reproduce? Thanks!
