### ISSUE TITLE
Installation: install GDAL/GEOS via brew on mac

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#409]
#### describe the issue

It would be good to mention [here](https://arches.readthedocs.io/en/latest/installing/requirements-and-dependencies/) that if on mac, GEOS and GDAL can be installed via Brew. It should be noted somewhere though that the specific file path of each has to be entered as kwargs in the project `settings.py` file like so:
`GDAL_LIBRARY_PATH = '/opt/homebrew/Cellar/gdal/3.8.4_3/lib/libgdal.34.3.8.4.dylib'`
`GEOS_LIBRARY_PATH = '/opt/homebrew/Cellar/geos/3.12.1/lib/libgeos_c.dylib'`

##### which release does this issue concern?

at least 7.x, possibly 6.2.x

**Comment by ekansa** [comment]
Closing this because of merged PR https://github.com/archesproject/arches-docs/pull/411

**Comment by jacobtylerwalls** [comment]
Tried a fresh install today and found this helpful article about using symlinks rather than local settings:
https://adamj.eu/tech/2024/03/20/django-homebrew-gdal-geos/
