### ISSUE TITLE
installation: mac install often requires manually adding postgres to PATH if not already

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#410]
#### describe the issue

In [this section](https://arches.readthedocs.io/en/latest/installing/installation/) it would be good to call out for mac installations that `pip install` will often fail because the installation of `psycopg` needs to access postgres' pg_config and does so by looking in the `PATH`. If a user downloaded the postgres app on mac (which we should also document if not already documented as an easy way to get postgres on mac) then they'll have to manually edit their profile like so:
```
nano ~/.zshrc

...
export PATH="/Applications/Postgres.app/Contents/Versions/16/bin:$PATH"

source ~/.zshrc
```
of course replacing `.zshrc` with whatever the user's bash profile is

I also notice on the page I linked to that we're calling out the GDAL kwarg in `settings.py` for windows users; we should do the same for mac users.

##### which release does this issue concern?

7.x

**Comment by ekansa** [comment]
Thanks! @whatisgalen . I'm not a mac user, so would you mind reviewing a PR I develop about this? (I can't test to make sure it works)

**Comment by whatisgalen** [comment]
> Thanks! @whatisgalen . I'm not a mac user, so would you mind reviewing a PR I develop about this? (I can't test to make sure it works)

For sure!

**Comment by ekansa** [comment]
Closing this with merged PR: https://github.com/archesproject/arches-docs/pull/411
