### ISSUE TITLE
delete_mapbox_layer command not yet documented

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#416]
#### describe the issue
The command for adding a mapbox layer is documented, but not `delete_mapbox_layer`. Users can delete with the following:
```
python manage.py packages -o delete_mapbox_layer -n "name of map layer to be deleted"
```

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/developing/reference/command-line-reference/#mapbox
https://arches.readthedocs.io/en/stable/developing/extending/creating-new-map-layers/#mapbox-layers

##### which release does this issue concern?
All - The command should be the same in all 6.2 - 7.x  versions.

**Comment by ekansa** [comment]
Updated all branches back to 6.2! Thanks for the heads up @chiatt !
