### ISSUE TITLE
Update Data Model documentation

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#43]
The data model documentation has not been updated for a while, though many changes have been made. 

This is a 4.2.0 effort, so stable/4.2.0 should be installed before running the model diagram software.

Work should be done on the existing `data_model_update` branch in this repo into which @beatboxchad has already migrated our existing docs. I'm publishing this branch here https://arches-dev.readthedocs.io/en/data_model_update/data-model.html so we can preview it in progress.

Steps to complete this update:

- [x] update the models diagrams (they were originally made with pygraphviz
        [here are my old notes on how to do that](https://github.com/archesproject/arches-docs/files/2103947/to.make.a.data.model.graph.txt)
- [x] In the section about Resource Models, the term Resource Class is used, as it was the original terminology. All of this terminology must be updated.
- [x] The graphic labeled "Resource Class" was made in Inkscape, and needs to be updated as per the resource model terminology.
        [resource-model-svg.zip](https://github.com/archesproject/arches-docs/files/2104102/resource-model.zip)
    - [x] Also, mentions of "Forms" in any graphics must be replaced with "Menus"
- [x] All of the model classes will need to be checked over, updated where necessary, and any new models (only in the Arches app) will also need to be added.
    - [x] add subheaders containing the model name above each code block
    - [x] reference these subheaders in the text above, in the _first_ occurrence of the model's name (if it occurrs). For example, in the Graph Definition text, link the first mention of "GraphModel" to the appropriate subheader below
    - [x] add the Function model to the end of the Graph Definition section, but leave out the description for now.

**Comment by beatboxchad** [comment]
In checking over the model classes, I found that there's no more Validation class.

I'm still researching, but it looks like it became a database table with datatypes in it and got a little more closely boxed with functions. This happened in August 2016, so we might be wanting to update docs from a certain version. Reading the relevant issues and PR's now.

**Comment by beatboxchad** [comment]
In the current code and in its recently-generated model graph, I see that functions have been mostly taken out. The only place I see Functions referred to is in GraphModel, by means of FunctionXGraph. In the UI, there are a couple pre-built Functions I can modify in trivial ways and associate with Resource Models, but I don't see how to make new ones or associate them in different contexts. I'm not sure yet what the current state/workflow/plans/whatnot is.

It looks like it was intended, back in 2016, to make Validations just a type of Function, and code/schema changes were made in response to https://github.com/archesproject/arches/issues/672. Subsequently all references to Validations were updated to refer to Functions.

You can see most of that here: https://github.com/archesproject/arches/pull/763/commits/d9fa0245b4533518ed19a9c471401c73d6d2172c

At some point later, further discussion/refactoring must have led to Functions being mostly excised. Maybe they went to the front-end as asynchronous JS -- there was talk of that, but I haven't looked just yet other than a little grep output. The only `self.functions` I see now is in `arches/app/models/graph.py` Some more git sleuthing, and I'll know the rest of the story as it pertains to the current data model.

Anybody who knows the story is welcome to weigh in. At any rate, as I document the data model for v4.2.x it looks like Functions do very little, and Validations no longer exist.

**Comment by mradamcox** [comment]
@beatboxchad, I'd say that "A Function instance can be used on any combination of Card, Node, and Widget instances." is actually still true, though perhaps a little confusing. As you noted, Functions are only "associated" with Resource Models, with the FunctionXGraph. However, a Function can be "used on" those entities because references to specific nodes (name node, for example) are embedded in a function for it to perform a certain task. I'm not sure if that makes sense, but here's my working documentation on Functions that I have not yet finished https://github.com/archesproject/arches/wiki/functions---draft. (This should be migrated to RTD too sooner than later.)

@adamlodge it would be great to get your input here too.

**Comment by adamlodge** [comment]
I dont have much to add besides to say that @beatboxchad is correct that Farallon internal thinking around the role of functions has evolved since 2016 toward use of data types and widgets for validation.  In theory, functions should still support various data process and auto-calculation tasks (ie auto-populate admin area based on spatial intersect of resource geometry and some admin layer), but in practice it has not been exercised very much yet.  I would love to see some patterns of use evolve and best practice get defined and documented.

**Comment by beatboxchad** [comment]
Right on, that's good context. It's especially useful to know that datatypes and widgets can be used for (among whatever else) validation; between that and the drafted Functions wiki doc @mradamcox linked, I think I understand the Big Picture at this point. Thank you both!

**Comment by beatboxchad** [comment]
(Being that this is for the data model documentation, details about what the attributes are for and how it relates back to Cards themselves are cool. Does this change the way Cards are used in any way, or does it just support a new workflow? Stuff like that. Let me know if you need more detailed questions from me.)

**Comment by robgaston** [comment]
@beatboxchad i'll focus on the db schema here as that seems to be your current focal point....

card components are a way for users to extend or overwrite the default behaviors of "cards" (the UI container for `tiles` in forms, reports, etc). for this feature, we introduced two new columns to the `cards` table and a new table `card_components`. the new columns on the `cards` table are:
`componentid` - a foreign key to the new `card_components` table that defines which card component should be used for a given card
`config` - a JSON object used to configure a card component. the expected schema of this object is defined by a card component developer (default values for this object are stored on the `card_components` records)

the `card_components` table is functionally the same as the `widgets` or `report_templates` tables, in that it is used to define the JS module and some metadata for a card component:
`componentid` - pk
`name` - a name to be displayed in the UI for this component
`description` - a description to be displayed in the UI for this component
`component` - a require path for the JS module representing this component
`componentname` - a knockout component name used by this component (for rendering via knockout's `component` binding handler)
`defaultconfig` - a default JSON configuration object to be used by cards that implement this component

i hope that helps clarify a bit - please let me know if you have other questions
