### ISSUE TITLE
The create_mapping_file command take only one graphid

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#444]
#### describe the issue
The [documentation for the create_mapping_file command ](https://arches.readthedocs.io/en/stable/developing/reference/command-line-reference/#other-data-management-commands )states that it takes one or more graphids. This is actually not the case. 

Instead of:
"One or more graph UUIDs to create a mapping for"

The description for the `-g` should read:
"The graph UUID for which to create a mapping"

##### please add links to existing docs or code (if relevant)
More details at the forum post: https://community.archesproject.org/t/arches-cli-mapping-file-export-does-not-tolerate-multiple-graph-ids/2479

##### which release does this issue concern?
all

**Comment by ekansa** [comment]
Implemented the fix @chiatt suggested
