### ISSUE TITLE
Consider adding some nuance to the section on CSRF_TRUSTED_ORIGINS

### ISSUE THREAD

**Issue by jacobtylerwalls** [archesproject/arches-docs#462]
#### describe the issue
Carlton Gibson's [post](https://noumenal.es/notes/til/django/csrf-trusted-origins/) on preferring `SECURE_PROXY_SSL_HEADER` over explicit configuration of `CSRF_TRUSTED_ORIGINS` might inspire us to add nuance or rewrite the section on CSRF_TRUSTED_ORIGINS.

At the very least we could link to it.

This is tricky business that regularly comes up on the forum.

**Comment by ekansa** [comment]
Thanks @jacobtylerwalls ! 

Ugh. This adds some new levels of complexity here. It would be nice to provide a straightforward good practice configuration for HTTPS deployment.
