### ISSUE TITLE
Docs show minimum node.js as 16 but release notes state 20.14.0

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches-docs#465]
#### describe the issue

The stable documents state that Node 16 is the recommended version.
![image](https://github.com/user-attachments/assets/228ca823-509d-463c-9cc6-ce454b94372f)

However, the 7.6 release notes suggest that the correct version is 20.14.0

![image](https://github.com/user-attachments/assets/5057eb0e-8263-4982-9f68-2e12c0dbcd4a)

##### please add links to existing docs or code (if relevant)

arches-docs: https://github.com/archesproject/arches-docs/blob/ee5426ff1743bf721e62b2309c0bfee149929cf1/docs/installing/requirements-and-dependencies.rst?plain=1#L41
new version referenced: https://github.com/archesproject/arches/blob/40590c89ed51186607447111242e251676acf214/releases/7.6.0.md?plain=1#L101

##### which release does this issue concern?

7.6

**Comment by ekansa** [comment]
Thanks @aj-he ! I made the update!
