### ISSUE TITLE
Lack of information about output files from export_business_data function

### ISSUE THREAD

**Issue by CWDamm-Kint** [archesproject/arches-docs#467]
#### describe the issue
Limited information on the output from the csv export_business_data function and how grouped data is handled. 

##### please add links to existing docs or code (if relevant)
See forum post:
https://community.archesproject.org/t/exporting-business-data-multiple-tiles-per-resource/2577

##### which release does this issue concern?
7.6

**Comment by ekansa** [comment]
Thanks! I made an update to the documentation. It took a bit of time to get to this because I needed to set up an instance of Arches with some relevant data to use for experimenting with export behaviors.
