### ISSUE TITLE
Document the ability to define the directory for project creation

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#6]
_From @jmunowitch on November 17, 2017 23:58_

The Docker setup uses the following command to create an arches project:
`arches-project create ${ARCHES_PROJECT} --directory ${ARCHES_PROJECT}`

The --directory variable can be documented for specifying the location of an Arches Project.

_Copied from original issue: archesproject/arches#2756_

**Comment by mradamcox** [comment]
This should probably just be a note in the main installation steps where a project is created. It would be a good bonus to add this command to the CLI docs at this time, but it's not necessary for this ticket.

**Comment by beatboxchad** [comment]
Looking at the code, the -d and --directory switches to this command both have the same effect.

This command appears in:
https://arches4.readthedocs.io/en/stable/creating-a-development-environment/
https://arches4.readthedocs.io/en/stable/installation/
https://arches4.readthedocs.io/en/stable/projects-and-packages/

I can add the switch according to the standard notation in each of those places, and it's not much trouble at all to add it to the CLI reference either.

PR coming up shortly.

**Comment by mradamcox** [comment]
all good!
