### ISSUE TITLE
Document how we add JavaScript dependencies to Arches

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-docs#61]
For new Arches developers how JS dependencies are added to the application may be unclear.  We should document this process to prevent developers from adding dependencies in a way that is inconsistent with our current pattern.

**Comment by mradamcox** [comment]
@chiatt Do you think you would be able to jot down a few notes here about this? I can do investigating on my own, but if it's something you could rattle off in 10 minutes that would be really helpful.

**Comment by mradamcox** [comment]
@chiatt from this ticket https://github.com/archesproject/arches/issues/4841 I'm gathering that for a developer to add a new `npm` package to arches they just have to enter `arches/install` and then run `yarn install new-package`... and then the new package is added to `package.json`. Is that right?

**Comment by chiatt** [comment]
Previously we copied the package.json from core Arches to the project when the project was created. The problem with this approach is that when Arches dependencies changed, then each project would have to be updated to reflect those changes. This caused a lot of frustration, especially after releases. @robgaston suggested that instead of managing all of the arches dependencies in two places, we make arches a dependency in the project. So, in the latest, the only dependency in a project’s `package.json` is arches itself.
```
{
    "name": "myproject",
    "dependencies": {
        "arches": "archesproject/arches#master"
    }
}
```
If you run yarn install on this file, all of the Arches dependencies (from ‘master’ in the example above) will download to your project’s packages directory. When you upgrade Arches, all you need to do is run yarn on your project’s package.json file, and you’ll get all of the changes - no need to manually update your project’s `package.json`.
The other advantage to this approach, is that it is easier to see what JS dependencies belong to your project. If I need to add extra dependencies to support my custom components, I can just add them to my project’s `package.json` as I would before, but now I can more clearly see which ones apply specifically to my project.
As an example Arches for Science will end up looking like this:
```
{
    "name": "afs",
    "repository": {
        "url": "git@github.com:archesproject/arches-for-science-prj.git",
        "type": "git"
    },
    "dependencies": {
        "arches": "archesproject/arches#master",
        "plotly.js-dist": "^1.52.2",
        "three": "^0.113.2"
    }
}
```
This is a pretty big improvement - but if your are developing a project, you may have to bear in mind where you are getting your arches dependencies from and make sure this line `"arches": "archesproject/arches#master"`  reflects the version of arches that you are working on.
