### ISSUE TITLE
Docs could provide a list of existing data types in Arches

### ISSUE THREAD

**Issue by veuncent** [archesproject/arches-docs#76]
#### describe the issue
Docs could provide a list of existing data types in Arches, perhaps like the [Glossary](https://arches.readthedocs.io/en/stable/glossary): name of the data type and a short description.

This may be overkill for some data types (e.g. string), but for e.g. `EDTF` this would be helpful.
The latter could describe that it concerns 'fuzzy dates' (helpful when using the search bar to explore this feature, makes it findable), and could provide an example, e.g. that edtf will support user inputs like 'Early 1st century'. 

##### which release does this issue concern?

all

**Comment by mradamcox** [comment]
@veuncent thanks for the suggestion, do you think a new appendix (like the glossary) would be appropriate for this? Also, maybe this could be combined with this new improved list of data type value formats for import. https://arches.readthedocs.io/en/stable/import-export/#import-value-formats

**Comment by BAPAlveyCHIC** [comment]
Hi Adam,
I'm not sure this is the right place to add my thoughts on this aspect of the documentation. But...

I also think that it would be valuable to add in the glossary/appendix how each of the data types can be configured in Arches.  

This is of particular relevance to the EDTF fields: I am at the moment trying to configure our edtf dates to a standard configuration, where:I am trying to limit my users to three definitions:

~   = 'approximate     = plus or minus 50 years
?   = 'uncertain'         = plus or minus 100 years
?~ = 'very uncertain' = plus or minus 200 years

Now I refer you to the attached image: this is part of the Arches Designer screens where the EDTF fields are configured.   The last three elements on this page I have defined as 50, 100, and 200 years respectively - although I am slightly concerned that the screen refers to these entries as 'Multipliers', so maybe I have misinterpreted the configuration? Some explanation of these in the documentation (and 'fuzzy padding') - perhaps in the proposed appendix  - with an example or two would be beneficial. 

(I would also be grateful for confirmation of this now!)

Best

Bryan

![ArchesEDTFDesigner](https://user-images.githubusercontent.com/16782478/54757841-f2d13600-4be2-11e9-872d-37fe4d50ada0.jpg)

**Comment by mradamcox** [comment]
Hi @BAPAlveyCHIC, thanks for the input. Hopefully @apeters can answer your question about the "multiplier" terminology. If I understand you correctly, you're saying that you expect these to be "buffers", as in "give or take 50 years", etc. instead of "this date x 50" -- which does seem like what the word multiplier would indicate.

Once we have that sorted out, I'll be happy to add it to the docs.

**Comment by apeters** [comment]
@mradamcox and @BAPAlveyCHIC the multiplier is applied to the padding value before the padding is applied to the date.  
For example if this EDTF date is given with the configs above: '1912-04~'
Then the fuzzy range would be `+- 50 months` (multipliers * padding) => (50*1)

**Comment by BAPAlveyCHIC** [comment]
Thanks for that @apeters.  I think this means that I've configured the dates as I wanted to using the configuration shown in the image of my previous message.  Cool.  I'll apply that to all my dates and then test to see if the search engine can pick them out.
