### ISSUE TITLE
Add export command to Resource Import/Export Documentation

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches-docs#77]
#### describe the issue
When reading the documentation it may not be obvious to a user what command to use to export business data as json while in the Resource Import/Export section of the documentation. It would be helpful to include the command or more links to the command line reference documentation to make it easier for users to find the business data import/export commands.

##### please add links to existing docs or code (if relevant)
https://arches.readthedocs.io/en/stable/import-export/

##### which release does this issue concern?
all

**Comment by mradamcox** [comment]
@ryan86 please review the new changes, I have already merged them in (along with some other improvements) https://arches.readthedocs.io/en/stable/import-export/

**Comment by mradamcox** [comment]
Closing now, these are small changes and I've asked for a review here and on slack, but haven't heard anything. Doesn't seem worth leaving this open, but it can be re-opened if necessary.
