### ISSUE TITLE
Update Data Models

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches-docs#97]
#### describe the issue
The data models in the docs haven't been updated since early (edit: summer) 2018. They need to be updated now.

##### which release does this issue concern?
latest and 4.4.1

**Comment by beatboxchad** [comment]
Are you referring to the graphviz-generated model diagrams in the Data Model documentation? I updated those for 4.2 as part of my work on #43. I guess that was all the way back in June.

This kind of thing is a great candidate for automation.

**Comment by mradamcox** [comment]
Oh yeah, @beatboxchad you're right. I was going off of old notes I had. Still would be good to update this. Yeah, even just wrapping the export in a management command would be helpful. Here are my own workflow notes on the process I've used in the past:

**Comment by beatboxchad** [comment]
\m/

Yeah, by "automation" I mean that a PR could be auto-generated upon release only if the models have changed. The graph_models command is a bit of magic between the pygraphviz library and Django's built-in apps module. You could use the latter to directly query the app models. Or, you could have the graph_models command generate a text-formatted file (there's an option for JSON) and parse that. Either way, there's lots of information in there you can use to automatically tell if an update is needed between this release and a previous one.

Reference:
https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/modelviz.py
https://stackoverflow.com/questions/1125107/django-how-can-i-find-a-list-of-models-that-the-orm-knows

**Comment by mradamcox** [comment]
in master now, will close once the commit has been cherry-picked to 4.4.1
